version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_db
    ports:
      - "5432:5432"

  loan_service:
    build: ./demande-pret-service
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq


  verification-credit-service:
    build: ./verification-credit-service
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq

  property_celery_worker:
    build: ./verification-credit-service
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis

  decision_service:
    build: ./decision-service
    depends_on:
      - rabbitmq

  eligibility_service:
    build: ./eligibilite-service
    depends_on:
      - rabbitmq

  rejection_service:
    build: ./rejet-service
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: